### ISSUE TITLE
Mistakenly specified coordinates

### ISSUE THREAD

**Issue by kokitsuyuzaki** [zamorarr/tensorr#15]
Hi, 

I found that the sptensor can accept the incompatible coordinates like below:

```
subs <- list(c(1,1,1,3,2), c(1,1,2,4,2), c(2,3,4,1,2), c(4,2,4,3,5), c(5,2,1,3,4))
# Values
vals <- c(10, 20, 30, 40, 50)
# Dimensions of tensor
dims <- c(3, 5, 7, 9, 11)
# Sparse Tensor
X2 <- sptensor(subs, vals, dims)
X2
```
In this example, the dimension of first mode is 3, but subs can be spcified in any range such as 1, 1, 2, 4, and 5.
Such mistakenly specified coordinates may cause some errors like below:

```R
unfold(X2, 1)
#  Matrix::sparseMatrix(i = i, j = j, x = vals, dims = newdims,  
#  all(dims >= dims.min) is not TRUE
```

I think when the sptensor is defined, such coordinates should be firstly checked and stopped if the values are mistakenly assigned.

Koki

**Comment by zamorarr** [comment]
Hi Koki. Thanks for spotting this. I'll look into it!

**Comment by lfaucheux** [comment]
*Since the title of this ticket is somehow related to my comment, I do it here.* Anyway, very nice package, which provides a very efficient way of dealing with multi-indexed/dimensional  objects in R.
My comment : don’t you think that what you are calling `dimnames`, or at least what you are [presenting](https://cran.r-project.org/web/packages/tensorr/vignettes/introduction.html#dimnames-indexing) as such,  should be renamed as  `coordnames` ?  Using the presented example, I mean that:
```
> dimnames(x) <- list(LETTERS[1:2], letters[1:2], month.abb[1:2])
> dimnames(x)
[[1]]        #<--- First dimension
[1] "A" "B"  #<--- First dimension‘s coordinates

[[2]]
[...]
```
Do you see my point ? Actually, it all boils down to a wording issue since, if instead of doing `dimnames(x) <- list(LETTERS[1:2], letters[1:2], month.abb[1:2])`, you rather do `dimnames(x) <- list(dim1=LETTERS[1:2], dim2=letters[1:2], dim3=month.abb[1:2])`, everything becomes (almost) conceptually valid. I have not been able to test it right now, but I guess that it would result in

```
$dim1
[1] "A" "B"
 
$dim2
[...]
```
Anyway, as already said, thank you very mush for this package.

**Comment by zamorarr** [comment]
Hi @kokitsuyuzaki . Thanks for your bug report. I have added a check when initializing sptensor that tests to see if the subscripts are valid. If you'd like to test it yourself before I merge it into master, you can re-install the package with:

```R
devtools::install_github("zamorarr/tensorr", ref = "fix-subs-range")
```

Your example should now provide the following error:

```R
subs <- list(c(1,1,1,3,2), c(1,1,2,4,2), c(2,3,4,1,2), c(4,2,4,3,5), c(5,2,1,3,4))
# Values
vals <- c(10, 20, 30, 40, 50)
# Dimensions of tensor
dims <- c(3, 5, 7, 9, 11)
# Sparse Tensor
X2 <- sptensor(subs, vals, dims)
```

```R
Error: dimensions of the tensor are 3 5 7 9 11 but these subscripts are outside the range:
	[4]: 5 2 1 3 4
	[5]: 4 2 4 3 5 
```

**Comment by zamorarr** [comment]
Hi @lfaucheux . I chose `dimnames()` in order to make the interface as similar to a standard R array as possible. `coordnames()` is also a good name, but since `dimnames()` is already used for dense arrays I think it's better to keep the function names the same.

I'm not sure I understand the second part of your question. You can in fact do `dimnames(x) <- list(dim1=LETTERS[1:2], dim2=letters[1:2], dim3=month.abb[1:2])` as you suggested. Am I missing something?

Thanks for using the package!
